import { useMemo, useState } from 'react';
import type { FormEvent, PointerEvent } from 'react';
import { ArrowRight, Crosshair, MapPin, Minus, Plus, Search, X } from 'lucide-react';
import type { Well } from '../types';

type Ranked = { well: Well; dist: string; score: number; geo: number; form: number; overlap: number; recent: number };
type Props = { wells: Well[]; active: Well; rank: Ranked[]; onWell: (well: Well) => void; onAdd: (well: Omit<Well,'id'> & {id?:string}) => Well };
const eventOf = (w: Well) => w.events[0];
const n = (v: number) => v.toLocaleString('en-US');

export default function OperationsMap({ wells, active, rank, onWell, onAdd }: Props) {
 const [term,setTerm]=useState(''),[status,setStatus]=useState('All statuses'),[eventFilter,setEventFilter]=useState('All events');
 const [selected,setSelected]=useState<Well|null>(null),[zoom,setZoom]=useState(1),[pan,setPan]=useState({x:0,y:0}),[drag,setDrag]=useState<{x:number;y:number;px:number;py:number}|null>(null);
 const [adding,setAdding]=useState(false),[pick,setPick]=useState(false),[form,setForm]=useState({id:'',name:'',field:'Upper Assam Basin',lat:'',lon:'',type:'Exploration' as NonNullable<Well['type']>,status:'Historical' as Well['status']});
 const visible=useMemo(()=>wells.filter(w=>(!term||`${w.id} ${w.name} ${w.field||''} ${w.formation}`.toLowerCase().includes(term.toLowerCase()))&&(status==='All statuses'||w.status===status)&&(eventFilter==='All events'||eventOf(w)?.type===eventFilter)),[wells,term,status,eventFilter]);
 const related=useMemo(()=>{if(!selected)return rank.slice(0,3);return wells.filter(w=>w.id!==selected.id).map(w=>{const dist=Math.sqrt(Math.pow((w.lat-selected.lat)*111,2)+Math.pow((w.lon-selected.lon)*94,2)),geo=Math.max(25,Math.round(100-dist*3)),form=w.formation===selected.formation?100:42,ev=eventOf(w),overlap=ev&&ev.type!=='No recorded event'&&ev.to>=selected.currentDepth-450&&ev.from<=selected.currentDepth+450?85:50,score=Math.round(geo*.35+form*.4+overlap*.25);return{well:w,dist:dist.toFixed(1),score,geo,form,overlap,recent:70}}).sort((a,b)=>b.score-a.score).slice(0,3)},[selected,wells,rank]);
 const coords=(w:Well)=>{const lats=wells.map(x=>x.lat),lons=wells.map(x=>x.lon),minLat=Math.min(...lats)-.025,maxLat=Math.max(...lats)+.025,minLon=Math.min(...lons)-.025,maxLon=Math.max(...lons)+.025;return{x:80+((w.lon-minLon)/(maxLon-minLon||1))*840,y:65+((maxLat-w.lat)/(maxLat-minLat||1))*480}};
 const selectMapPoint=(e:PointerEvent<SVGSVGElement>)=>{if(!pick)return;const rect=e.currentTarget.getBoundingClientRect(),sx=(e.clientX-rect.left)/rect.width*1000,sy=(e.clientY-rect.top)/rect.height*620;const x=(sx-pan.x)/zoom,y=(sy-pan.y)/zoom;const lats=wells.map(w=>w.lat),lons=wells.map(w=>w.lon);const minLat=Math.min(...lats)-.025,maxLat=Math.max(...lats)+.025,minLon=Math.min(...lons)-.025,maxLon=Math.max(...lons)+.025;setForm(v=>({...v,lat:(maxLat-((y-65)/480)*(maxLat-minLat)).toFixed(5),lon:(minLon+((x-80)/840)*(maxLon-minLon)).toFixed(5)}));setPick(false);setAdding(true)};
 const submit=(e:FormEvent)=>{e.preventDefault();const lat=Number(form.lat),lon=Number(form.lon);if(!form.name.trim()||!Number.isFinite(lat)||!Number.isFinite(lon)||lat < -90||lat>90||lon < -180||lon>180)return;const created=onAdd({id:form.id.trim()||undefined,name:form.name.trim(),field:form.field,lat,lon,type:form.type,status:form.status,spud:new Date().toISOString().slice(0,10),totalDepth:0,currentDepth:0,formation:'Formation not assigned',phase:form.status==='Active'?'Drilling':'Planned',events:[{id:`EV-${form.id||Date.now()}`,type:'No recorded event',from:0,to:0,date:new Date().toISOString().slice(0,10),severity:'Low',summary:'No historical event records are attached to this new prototype well.',report:'Not available',page:1,confidence:0}]});setSelected(created);setAdding(false);setForm({id:'',name:'',field:'Upper Assam Basin',lat:'',lon:'',type:'Exploration',status:'Historical'});};
 return <div className="ops-map-page">
  <div className="page-heading"><div><div className="eyebrow">OPERATIONS · SPATIAL WELL REGISTER</div><h1>Operations map</h1><p>Explore the synthetic field, inspect well context, and identify nearby offsets.</p></div><div className="heading-actions"><button className="secondary-btn" onClick={()=>setAdding(true)}><Plus size={15}/> Add Well</button></div></div>
  <div className="ops-map-toolbar"><label className="ops-map-search"><Search size={15}/><input value={term} onChange={e=>setTerm(e.target.value)} placeholder="Search well, field, formation…"/></label><select value={status} onChange={e=>setStatus(e.target.value)}><option>All statuses</option><option>Active</option><option>Historical</option></select><select value={eventFilter} onChange={e=>setEventFilter(e.target.value)}><option>All events</option>{['Lost circulation','Stuck pipe','Kick','NPT','Equipment failure'].map(x=><option key={x}>{x}</option>)}</select><span className="ops-map-count">{visible.length} of {wells.length} wells</span></div>
  <div className="ops-map-grid"><section className="panel ops-map-panel"><div className="ops-map-heading"><div><b>Upper Assam Basin · synthetic coordinates</b><small>Click a marker for well context · drag to pan · use controls to zoom</small></div><span className="synthetic-tag"><span/> DEMO MAP</span></div>
   <div className="ops-map-viewport"><svg viewBox="0 0 1000 620" onPointerDown={e=>{if(pick){selectMapPoint(e);return}e.currentTarget.setPointerCapture(e.pointerId);setDrag({x:e.clientX,y:e.clientY,px:pan.x,py:pan.y})}} onPointerMove={e=>{if(drag)setPan({x:drag.px+e.clientX-drag.x,y:drag.py+e.clientY-drag.y})}} onPointerUp={()=>setDrag(null)} onPointerCancel={()=>setDrag(null)} onDoubleClick={e=>{e.preventDefault();setZoom(z=>Math.min(2.8,z+.15))}} style={{cursor:pick?'crosshair':drag?'grabbing':'grab'}} role="img" aria-label="Interactive synthetic well map">
    <g transform={`translate(${pan.x} ${pan.y}) scale(${zoom})`}>
     <path d="M-20 205 C140 150 215 270 360 230 S610 145 760 220 S950 250 1040 180" fill="none" stroke="#bfdbd5" strokeWidth="20" opacity=".55"/><path d="M-20 205 C140 150 215 270 360 230 S610 145 760 220 S950 250 1040 180" fill="none" stroke="#8abbb2" strokeWidth="2" strokeDasharray="8 9"/>
     {[0,1,2,3].map(i=><path key={i} d={`M${-30+i*60} ${420+i*25} C240 ${380+i*13} 410 ${510-i*17} 630 ${410+i*16} S850 ${380+i*9} 1030 ${470-i*15}`} fill="none" stroke="#d2cbbb" strokeWidth="1.2"/>)}
     <path d="M90 70 L280 155 L420 120 L605 196 L825 140 L950 240" fill="none" stroke="#c8d5df" strokeWidth="3" strokeDasharray="10 7"/><text x="90" y="98" className="ops-map-label">NORTH FIELD</text><text x="718" y="495" className="ops-map-label">EAST BLOCK</text>
     {visible.map(w=>{const p=coords(w),isActive=w.id===active.id,isSelected=w.id===selected?.id,ev=eventOf(w);return <g key={w.id} className="ops-map-marker" transform={`translate(${p.x} ${p.y})`} onPointerDown={e=>e.stopPropagation()} onClick={()=>setSelected(w)}>
       <circle r={isSelected?20:15} fill={isActive?'#0e6074':w.status==='Active'?'#149a81':ev&&ev.type!=='No recorded event'?'#d99836':'#64829a'} opacity=".18"/><circle r={isSelected?9:7} fill={isActive?'#0e6074':w.status==='Active'?'#149a81':ev&&ev.type!=='No recorded event'?'#d99836':'#64829a'} stroke="white" strokeWidth="2.5"/><text x="13" y="4" className="ops-marker-label">{w.id.replace('OIL-SYN-','')}</text><rect x="-18" y="-20" width="36" height="38" fill="transparent"/><title>{w.name} · {w.status}</title>
      </g>})}
     {pick&&form.lat&&form.lon&&<circle cx={coords({lat:Number(form.lat),lon:Number(form.lon)} as Well).x} cy={coords({lat:Number(form.lat),lon:Number(form.lon)} as Well).y} r="11" fill="none" stroke="#c43f39" strokeWidth="3" strokeDasharray="4 3"/>}
    </g>
   </svg><div className="ops-map-controls"><button aria-label="Zoom in" onClick={()=>setZoom(z=>Math.min(3,z+.2))}><Plus size={15}/></button><button aria-label="Zoom out" onClick={()=>setZoom(z=>Math.max(.7,z-.2))}><Minus size={15}/></button><button onClick={()=>{setZoom(1);setPan({x:0,y:0})}}>Fit</button></div><div className="ops-map-legend"><span><i className="legend-live"/>Active well</span><span><i className="legend-historical"/>Historical</span><span><i className="legend-event"/>Has event evidence</span></div>{pick&&<div className="map-pick-hint"><Crosshair size={14}/> Click map to place well coordinates <button onClick={()=>setPick(false)}>Cancel</button></div>}</div>
   <div className="ops-map-foot"><span><MapPin size={13}/> Fictional locations · illustrative only</span><button onClick={()=>setAdding(true)}><Plus size={13}/> Add well</button></div>
  </section>
  <aside className="panel map-well-side"><div className="panel-heading"><div><div className="panel-title">{selected?'Well summary':'Select a well'}</div><div className="panel-sub">{selected?'Operational context and nearby offsets':'Click any marker to inspect it'}</div></div></div>{selected?<><div className="map-selected-well"><span className={`status-pill ${selected.status==='Active'?'active':'indexed'}`}>{selected.status.toUpperCase()}</span><h2>{selected.name}</h2><p>{selected.field||'Upper Assam Basin'} · {selected.type||'Well'} · {selected.phase}</p><div className="map-well-facts"><span>LATITUDE<b>{selected.lat.toFixed(5)}°</b></span><span>LONGITUDE<b>{selected.lon.toFixed(5)}°</b></span><span>CURRENT DEPTH<b>{n(selected.currentDepth)} m</b></span><span>TOTAL DEPTH<b>{n(selected.totalDepth)} m</b></span></div><div className="map-event-summary"><b>{eventOf(selected)?.type==='No recorded event'?'HISTORICAL EVIDENCE':'LATEST HISTORICAL EVENT'}</b><p>{eventOf(selected)?.type==='No recorded event'?'No event records attached yet.':`${eventOf(selected)?.type} · ${n(eventOf(selected)?.from||0)}–${n(eventOf(selected)?.to||0)} m`}</p></div><button className="primary-btn map-open-detail" onClick={()=>onWell(selected)}>Open Well Detail <ArrowRight size={14}/></button></div><div className="map-nearby"><b>Nearby offset wells</b>{related.length?related.map(r=><button key={r.well.id} onClick={()=>setSelected(r.well)}><span><b>{r.well.name}</b><small>{r.dist} km · {r.well.formation}</small></span><strong>{r.score}<small> MATCH</small></strong></button>):<small>No offset matches in the current list.</small>}</div></>:<div className="map-empty">Choose a well marker to see its summary, location, and nearest comparables.</div>}</aside></div>
  {adding&&<div className="well-modal-backdrop" onClick={()=>setAdding(false)}><form className="panel add-well-modal" onSubmit={submit} onClick={e=>e.stopPropagation()}><div className="panel-heading"><div><div className="panel-title">Add well to demo map</div><div className="panel-sub">New records stay in this browser session and use synthetic data.</div></div><button type="button" className="icon-btn" onClick={()=>setAdding(false)} aria-label="Close form"><X size={16}/></button></div><div className="add-well-form-grid"><label>WELL ID <input placeholder="Auto-generated if blank" value={form.id} onChange={e=>setForm(v=>({...v,id:e.target.value}))}/></label><label>WELL NAME <input required value={form.name} onChange={e=>setForm(v=>({...v,name:e.target.value}))} placeholder="e.g. OIL-SYN-013"/></label><label>FIELD <input required value={form.field} onChange={e=>setForm(v=>({...v,field:e.target.value}))}/></label><label>TYPE <select value={form.type} onChange={e=>setForm(v=>({...v,type:e.target.value as NonNullable<Well['type']>}))}><option>Producer</option><option>Injector</option><option>Exploration</option><option>Appraisal</option></select></label><label>STATUS <select value={form.status} onChange={e=>setForm(v=>({...v,status:e.target.value as Well['status']}))}><option>Historical</option><option>Active</option></select></label><label>LATITUDE <input required type="number" step="0.00001" min="-90" max="90" value={form.lat} onChange={e=>setForm(v=>({...v,lat:e.target.value}))}/></label><label>LONGITUDE <input required type="number" step="0.00001" min="-180" max="180" value={form.lon} onChange={e=>setForm(v=>({...v,lon:e.target.value}))}/></label></div><button type="button" className="secondary-btn map-pick-button" onClick={()=>{setAdding(false);setPick(true)}}><Crosshair size={14}/> Choose coordinates on map</button><div className="add-well-actions"><button type="button" className="quiet-btn" onClick={()=>setAdding(false)}>Cancel</button><button className="primary-btn" type="submit">Add well <ArrowRight size={14}/></button></div></form></div>}
 </div>;
}
