import { Activity, AlertTriangle, ArrowRight, ChevronDown, FileText, MapPin, Radio, ShieldCheck } from 'lucide-react';
import { Line, LineChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import type { Alert, Well } from '../types';
import { telemetry } from '../data/mockData';

type Props={well:Well;allWells:Well[];rank:{well:Well;dist:string;score:number}[];alerts:Alert[];go:(page:any)=>void;onEvidence:(well:Well)=>void;onReview:(alert:Alert)=>void;onSetActive:(well:Well)=>void};
const n=(x:number)=>x.toLocaleString('en-US');
export default function WellDetail({well,allWells,rank,alerts,go,onEvidence,onReview,onSetActive}:Props){
 const events=well.events.filter(e=>e.type!=='No recorded event');
 const relevant=allWells.filter(w=>w.id!==well.id).map(w=>{const distance=Math.sqrt(Math.pow((w.lat-well.lat)*111,2)+Math.pow((w.lon-well.lon)*94,2)),geo=Math.max(25,Math.round(100-distance*3)),formation=w.formation===well.formation?100:42,event=w.events.find(e=>e.type!=='No recorded event'),depth=event&&event.from<=well.currentDepth+450&&event.to>=well.currentDepth-450?84:50,score=Math.round(geo*.35+formation*.4+depth*.25);return{well:w,dist:distance.toFixed(1),score}}).sort((a,b)=>b.score-a.score).slice(0,3);
 const pointX=140,pointY=34+Math.min(148,well.currentDepth/4500*148);
 return <>
  <div className="page-heading"><div><div className="eyebrow">WELL RECORD · SYNTHETIC</div><h1>{well.name}</h1><p>{well.field||'Upper Assam Basin'} · {well.type||'Well'} · {well.formation} · {well.phase}</p></div><div className="heading-actions"><button className="secondary-btn" onClick={()=>go('Operations map')}><MapPin size={14}/> Back to map</button><button className="primary-btn" onClick={()=>go('Knowledge search')}>Search this well <ArrowRight size={14}/></button></div></div>
  <section className="well-hero"><div className="well-hero-main"><span className={`status-pill ${well.status==='Active'?'active':'indexed'}`}>● {well.status.toUpperCase()}</span><h2>{well.name}</h2><p>{well.field||'Upper Assam Basin'} <span>·</span> {well.type||'Well'} <span>·</span> {well.phase}</p></div><div className="well-hero-metric"><small>CURRENT DEPTH</small><b>{n(well.currentDepth)} <i>m</i></b></div><div className="well-hero-metric"><small>TOTAL DEPTH</small><b>{well.totalDepth?n(well.totalDepth):'Not recorded'} <i>{well.totalDepth?'m':''}</i></b></div><div className="well-hero-metric"><small>COORDINATES</small><b>{well.lat.toFixed(4)}°</b><small>{well.lon.toFixed(4)}°</small></div></section>
  <div className="well-profile-note"><b>Well at a glance</b><p>{well.status==='Active'?'Active operational context with synthetic replay telemetry available.':'Historical/planned well record for offset comparison.'} {events.length?`${events.length} source-linked historical event${events.length===1?'':'s'} attached.`:'No historical events or source documents are attached to this well yet.'}</p><button className="text-link" onClick={()=>go('Operations map')}>View spatial context <ArrowRight size={12}/></button></div>
  <details className="well-record-disclosure"><summary><span>Explore detailed well record</span><span>Trajectory · telemetry · events · documents <ChevronDown size={15}/></span></summary>
   <div className="details-two"><section className="panel"><div className="panel-heading"><div><div className="panel-title">Trajectory & depth</div><div className="panel-sub">Illustrative profile · coordinates and geometry are synthetic</div></div><span className="synthetic-tag"><span/> SYNTHETIC</span></div><div className="well-trajectory"><svg viewBox="0 0 360 210" role="img" aria-label="Illustrative well trajectory and current depth"><path d="M35 28H330 M35 75H330 M35 122H330 M35 169H330" stroke="#e6ecee"/><text x="6" y="31">0 m</text><text x="2" y="78">1,500</text><text x="2" y="125">3,000</text><text x="2" y="172">4,500</text><path d={`M${pointX} 25 C${pointX+10} 70 ${pointX-40} 100 ${pointX+28} ${pointY}`} fill="none" stroke="#1686a0" strokeWidth="4" strokeLinecap="round"/><circle cx={pointX+28} cy={pointY} r="7" fill="#c94a43" stroke="#fff" strokeWidth="3"/><text x={pointX+42} y={pointY+4} className="trajectory-label">CURRENT BIT · {n(well.currentDepth)} m</text></svg><div className="trajectory-foot"><span><i/> Well path</span><span><b/> Current depth</span><small>Not a survey-grade trajectory</small></div></div><div className="well-coordinate-row"><span><MapPin size={13}/> {well.lat.toFixed(5)}, {well.lon.toFixed(5)}</span><span>{well.phase} · {well.status}</span></div></section>
    <section className="panel"><div className="panel-heading"><div><div className="panel-title">Telemetry snapshot</div><div className="panel-sub">Replay-shaped demonstration values</div></div><Radio size={15}/></div><div className="chart-wrap params-chart"><ResponsiveContainer width="100%" height="100%"><LineChart data={telemetry}><XAxis dataKey="depth" tick={{fontSize:9}}/><YAxis tick={{fontSize:9}}/><Tooltip/><Line dataKey="rop" name="ROP" stroke="#00a4c7" dot={false} strokeWidth={2}/><Line dataKey="torque" name="Torque" stroke="#5b6ee1" dot={false} strokeWidth={2}/></LineChart></ResponsiveContainer></div><div className="chart-legend"><span><i className="dot-cyan"/> Rate of penetration</span><span><i className="dot-purple"/> Torque</span></div><button className="text-link" onClick={()=>go('Current well')}>Open replay controls <ArrowRight size={12}/></button></section></div>
   <div className="details-two"><section className="panel"><div className="panel-heading"><div><div className="panel-title">Historical events</div><div className="panel-sub">Source-linked records · {events.length} event{events.length===1?'':'s'}</div></div></div>{events.length?events.map(e=><article className="timeline-entry" key={e.id}><div className="timeline-stem"><i/></div><div className="timeline-body"><div className="timeline-meta"><span className="severity-pill high">{e.severity.toUpperCase()}</span><span>{e.date}</span></div><h3>{e.type} · {n(e.from)}–{n(e.to)} m</h3><p>{e.summary}</p><button className="citation-link" onClick={()=>onEvidence(well)}><FileText size={13}/>{e.report}.pdf · page {e.page}<ArrowRight size={12}/></button></div></article>):<div className="well-empty-history"><ShieldCheck size={18}/> No historical event records are attached. Add verified records through the document workflow.</div>}</section>
    <section className="panel"><div className="panel-heading"><div><div className="panel-title">Related evidence & alerts</div><div className="panel-sub">Review the source before acting</div></div></div>{events.length?events.map(e=><div className="evidence-summary" key={e.id}><div className="evidence-doc-icon"><FileText size={19}/></div><div><b>{e.report}.pdf</b><small>{well.name} · {e.date} · page {e.page}</small></div><button className="text-link" onClick={()=>onEvidence(well)}>Open <ArrowRight size={12}/></button></div>):<div className="well-empty-history">No supporting reports linked to this well.</div>}{alerts.length?alerts.map(a=><div className="well-alert-row" key={a.id}><AlertTriangle size={15}/><span><b>{a.type} · {a.status}</b><small>{n(a.from)}–{n(a.to)} m · {a.severity} attention</small></span><button className="text-link" onClick={()=>onReview(a)}>Review <ArrowRight size={11}/></button></div>):<div className="well-empty-history">No review alerts for this well.</div>}</section></div>
   <section className="panel well-offset-disclosure"><div className="panel-heading"><div><div className="panel-title">Nearby offset context</div><div className="panel-sub">Screening factors, not event probabilities</div></div><button className="text-link" onClick={()=>{onSetActive(well);go('Offset wells')}}>Compare offsets <ArrowRight size={12}/></button></div>{relevant.length?relevant.map(r=><button key={r.well.id} onClick={()=>{onSetActive(well);go('Offset wells')}}><span><b>{r.well.name}</b><small>{r.well.formation} · {r.dist} km · {r.well.events.filter(e=>e.type!=='No recorded event').length} historical events</small></span><strong>{r.score}<small> MATCH</small></strong></button>):<div className="well-empty-history">No nearby offsets available.</div>}</section>
  </details>
 </>;
}
